### ISSUE TITLE
for protein file it shows as 'IFeatureOmegaGui' object has no attribute 'proteinKNN'

### ISSUE THREAD

**Issue by Sathya1007** [Superzchen/iFeatureOmega-GUI#1]
Whenever i try to open a protein sequence file it always shows a error as this
Traceback (most recent call last):
  File "C:\Users\sathy\anaconda3\envs\gui\lib\site-packages\iFeatureOmegaGUI\iFeatureOmegaGUI.py", line 2274, in get_fasta_file_name
    self.check_protein_descriptors()
  File "C:\Users\sathy\anaconda3\envs\gui\lib\site-packages\iFeatureOmegaGUI\iFeatureOmegaGUI.py", line 2258, in check_protein_descriptors
    self.proteinKNN.setDisabled(True)
AttributeError: 'IFeatureOmegaGui' object has no attribute 'proteinKNN'

i installed everything that is given in the manual.

I look forward from hearing from you soon.

**Comment by soulorlong** [comment]
me too

**Comment by Iamzhangzixin** [comment]
me too

**Comment by AmamiyaHoshie** [comment]
me too

**Comment by DaniloVFreire** [comment]
I am having the same issue

**Comment by DaniloVFreire** [comment]
I have found a simple workaround. I don't know why those lines are commented out, but if you uncomment them, the protein feature extraction will work.

Please uncomment lines 634 to 638 in the iFeatureOmegaGUI.py file:

```python
# self.proteinKNN = QTreeWidgetItem(self.Protein)
# self.proteinKNN.setText(0, 'KNN')
# self.proteinKNN.setText(1, 'K-nearest neighbor')
# self.proteinKNN.setCheckState(0, Qt.Unchecked)
# self.proteinKNN.setToolTip(1, 'The KNN descriptor depicts how much one query sample resembles other samples.')
```
Just remove the # at the beginning of each line, and everything should work fine!  

After that, just run `python iFeatureOmegaGUI.py` with all the required packages installed.
